
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/bsab123/spring-cloud-netflix
          search-paths: respo
          username: bsab123
          password: xjx279205343

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/