spring:
  application:
    name: spring-cloud-service-provider
  cloud:
    config:
      uri: http://localhost:8888
      name: provider-dev
      label: master
      profile: dev


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/