base:
  config:
    nacos:
      hostname: 139.224.117.172
      port: 8848
    redis:
      hostname: 47.100.220.7
      port: 6379
    datasource:
      hostname: 139.224.117.172
      port: 3306



spring:
  application:
    name: spring-cloud-service-provider
  rabbitmq:
    host: 47.100.220.7
    port: 5672
    username: rabbit
    password: 123456

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.datasource.hostname}:${base.config.datasource.port}/classroom?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    elasticsearch:
      cluster-name: es750
      cluster-nodes: 47.100.220.7:9300
server:
  port: 8762
  servlet:
    context-path: /provider

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
